# Generated by Django 4.0.6 on 2022-07-11 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='His',
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'get_latest_by': ['creation_date']},
        ),
        migrations.AddField(
            model_name='location',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
